# Generated by Django 5.0.1 on 2024-01-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_first',
            old_name='text',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='history_second',
            old_name='text',
            new_name='second',
        ),
    ]
