# Generated by Django 5.0.1 on 2024-01-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_text_history_first_first_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_first',
            old_name='first',
            new_name='hero',
        ),
        migrations.RenameField(
            model_name='history_second',
            old_name='second',
            new_name='about',
        ),
    ]
