# Generated by Django 5.0.1 on 2024-01-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_history_second_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_second',
            name='about',
            field=models.CharField(max_length=3000),
        ),
    ]
