# Generated by Django 5.0.1 on 2024-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_born_delete_opportunities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_salary', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='AllVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_vacancy', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='CppSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpp_salary', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='CppVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpp_vacancy', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='DemandHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_header', models.CharField(max_length=500)),
            ],
        ),
    ]
