# Generated by Django 5.0.1 on 2024-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_allsalaryimg_allsalary_titleas_allvacancy_titleav_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imageAS', models.ImageField(upload_to='images')),
                ('imageAV', models.ImageField(upload_to='images')),
                ('imageCS', models.ImageField(upload_to='images')),
                ('imageCV', models.ImageField(upload_to='images')),
            ],
        ),
    ]
