# Generated by Django 5.0.1 on 2024-01-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_alter_image_imageas_alter_image_imageav_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_salary', models.ImageField(blank=True, upload_to='images')),
                ('vacancy_rate', models.ImageField(blank=True, upload_to='images')),
                ('city_salary_cpp', models.ImageField(blank=True, upload_to='images')),
                ('vacancy_rate_cpp', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
