# Generated by Django 5.0.1 on 2024-01-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_citysalary_citysalarycpp_vacancyrate_vacancyratecpp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('text', models.CharField(max_length=4000)),
            ],
        ),
    ]
