# Generated by Django 5.0.1 on 2024-01-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_geographyheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('text', models.CharField(max_length=4000)),
                ('table', models.CharField(max_length=15000)),
            ],
        ),
        migrations.CreateModel(
            name='BestSkillsCpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('text', models.CharField(max_length=4000)),
                ('table', models.CharField(max_length=15000)),
            ],
        ),
    ]
