# Generated by Django 5.0.1 on 2024-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_bestskills_bestskillscpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestskillscpp',
            name='table',
            field=models.TextField(max_length=15000),
        ),
    ]
